name: Deploy release
on:
  push:
    tags:
      - '*'

concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftps
        server-dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          scripts/*
          .eslintrc
          LICENSE
          package.json
          README.md
          yarn.lock
